This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./master_thesis_s1000522.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file master_thesis_s1000522.acn....done (168 entries accepted, 0 rejected).
Sorting entries.....done (1669 comparisons).
Generating output file master_thesis_s1000522.acr....done (97 lines written, 0 warnings).
Output written in master_thesis_s1000522.acr.
Transcript written in master_thesis_s1000522.alg.
